tokengenerate/accounts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views as local_views
from rest_framework.authtoken import views as rest_framework_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'api/users^$', views.UserCreate.as_view(), name='account-create'),
    url(r'^login/$', local_views.get_auth_token, name='login'),
    url(r'^logout/$', local_views.logout_user, name='logout'),
    url(r'^auth/$',  local_views.login_form, name='login_form'),
    url(r'^get_auth_token/$', rest_framework_views.obtain_auth_token, name='get_auth_token'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tokengenerate/polls/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views, api_views


urlpatterns = [
    # Regular Django Views
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # API views
    url(r'^api/questions/$', api_views.QuestionList.as_view()),
    url(r'^api/questions/(?P<pk>[0-9]+)/$', api_views.QuestionDetail.as_view()),
    url(r'^api/choices/(?P<pk>[0-9]+)/$', api_views.ChoiceDetail.as_view()),
    url(r'^api/create_user/$', api_views.UserCreate.as_view()),
    url(r'^api/users/(?P<pk>[0-9]+)/$', api_views.UserDetail.as_view()),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tokengenerate/tokengenerate/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Regular Django urls
    url(r'^polls/',    include('polls.urls', namespace="polls")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^admin/', include(admin.site.urls)),
]

tokengenerate/accounts/models.py
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

# chris 5674e8d0c9408476f8b89dee85d4e08003649cfa
# bob 667594d84815c46eea4c38eb9a686010a1e1db66
# new_user 5f05673bd6ab749fe50832633249a201a13acdc5
# admin 93138ba960dfb4ef2eef6b907718ae04400f606a

tokengenerate/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name="choices")
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

tokengenerate/accounts/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from rest_framework.authtoken.models import Token
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from accounts.serializers import UserSerializer
from django.contrib.auth.models import User

class UserCreate(APIView):
    """
    Creates the user.
    """

    def post(self, request, format='json'):
        return Response('hello')

def logout_user(request):
    return render(request, 'accounts/logout.html', {})

def login_form(request):
    return render(request, 'accounts/login.html', {})

def get_auth_token(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        # the password verified for the user
        if user.is_active:
            token, created = Token.objects.get_or_create(user=user)
            request.session['auth'] = token.key
            return redirect('/polls/', request)
    return redirect(settings.LOGIN_URL, request)

tokengenerate/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import Choice, Question

def index(request):
    template_name = 'polls/index.html'
    questions = Question.objects.order_by('-pub_date')[:5]
    context = {
        "questions": questions,
        "login_url": settings.LOGIN_URL
    }
    return render(request, template_name, context)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choices.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

tokengenerate/accounts/templates/accounts/login.html
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

{% csrf_token %}
Username: <input type='text' name='username' id='username' />
<br>
Password: <input type='password' name='password' id='password' />
<br>
<input type='submit' value='Login' id='login_form' />

<script>
  $("#login_form").on("click", function(e) {
    var username = $("#username").val();
    var password = $("#password").val();

    $.post("/accounts/get_auth_token/", {"username": username, "password": password})
      .success(function(data) {
        var token = data["token"];
        document.cookie = 'token='+token+";path=/";
        window.location.href = "/polls/";
      });
  });
</script>

tokengenerate/accounts/templates/accounts/logout.html
<script>
document.cookie = "token=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/";
location.href="/accounts/auth/";
</script>

tokengenerate/polls/templates/polls/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Angular + Django</title>
        <script src="{% static 'angular/angular.min.js' %}"></script>
        <script src="{% static 'angular/angular-cookies.min.js' %}"></script>
        <script src="{% static 'angular/angular-route.min.js' %}"></script>
        <script src="{% static 'app.js' %}"></script>
        <script>
        // Configuration information
        var login_url = "{{ login_url }}";
        </script>
    </head>
    <body ng-app="pollsApp">

      {% verbatim %}
        <div ng-controller="PollsController">
          <div ng-view>
          </div>
        </div>
      {% endverbatim %}

    </body>
</html>

tokengenerate/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

tokengenerate/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

tokengenerate/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>